DELIMITER ;
INSERT INTO `ds` (`table_name`, `title`, `reorderfield`, `use_history`, `searchfield`, `displayfield`, `sortfield`, `searchany`, `hint`, `overview_tpl`, `sync_table`, `writetable`, `globalsearch`, `listselectionmodel`, `sync_view`, `syncable`, `cssstyle`, `alternativeformxtype`, `read_table`, `class_name`, `special_add_panel`, `existsreal`, `character_set_name`, `read_filter`, `listxtypeprefix`, `phpexporter`, `phpexporterfilename`, `combined`, `default_pagesize`, `allowForm`, `listviewbaseclass`, `showactionbtn`, `modelbaseclass`) VALUES ('papervote_optical','Stimmzettelscan',NULL,NULL,'ballotpaper_id','ballotpaper_id','ballotpaper_id',NULL,NULL,NULL,NULL,NULL,NULL,'cellmodel',NULL,NULL,NULL,NULL,NULL,'Wahlsystem',NULL,1,NULL,NULL,NULL,'XlsxWriter','papervote_optical_{DATE}',0,1000,1,'Tualo.DataSets.ListView',1,'Tualo.DataSets.model.Basic') ON DUPLICATE KEY UPDATE title=VALUES(title), reorderfield=VALUES(reorderfield), use_history=VALUES(use_history), searchfield=VALUES(searchfield), displayfield=VALUES(displayfield), sortfield=VALUES(sortfield), searchany=VALUES(searchany), hint=VALUES(hint), overview_tpl=VALUES(overview_tpl), sync_table=VALUES(sync_table), writetable=VALUES(writetable), globalsearch=VALUES(globalsearch), listselectionmodel=VALUES(listselectionmodel), sync_view=VALUES(sync_view), syncable=VALUES(syncable), cssstyle=VALUES(cssstyle), alternativeformxtype=VALUES(alternativeformxtype), read_table=   VALUES(read_table), class_name=VALUES(class_name), special_add_panel=VALUES(special_add_panel), existsreal=VALUES(existsreal), character_set_name=VALUES(character_set_name), read_filter=VALUES(read_filter), listxtypeprefix=VALUES(listxtypeprefix), phpexporter=VALUES(phpexporter), phpexporterfilename=VALUES(phpexporterfilename), combined=VALUES(combined), default_pagesize=VALUES(default_pagesize), allowForm=VALUES(allowForm), listviewbaseclass=VALUES(listviewbaseclass), showactionbtn=VALUES(showactionbtn), modelbaseclass=VALUES(modelbaseclass);
INSERT  IGNORE INTO `ds_column` (`table_name`, `column_name`, `default_value`, `default_max_value`, `default_min_value`, `update_value`, `is_primary`, `syncable`, `referenced_table`, `referenced_column_name`, `is_nullable`, `is_referenced`, `writeable`, `note`, `data_type`, `column_key`, `column_type`, `character_maximum_length`, `numeric_precision`, `numeric_scale`, `character_set_name`, `privileges`, `existsreal`, `deferedload`, `hint`, `fieldtype`) VALUES ('papervote_optical','ballotpaper_id',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NO',NULL,1,NULL,'int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,NULL,NULL,''),
('papervote_optical','box_id',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NO',NULL,1,NULL,'varchar','','varchar(32)',32,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('papervote_optical','created',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NO',NULL,1,NULL,'time','','timestamp',NULL,NULL,NULL,NULL,'select,insert,update,references',1,NULL,NULL,''),
('papervote_optical','marks',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NO',NULL,1,NULL,'varchar','','varchar(255)',255,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('papervote_optical','modified',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NO',NULL,1,NULL,'time','','timestamp',NULL,NULL,NULL,NULL,'select,insert,update,references',1,NULL,NULL,''),
('papervote_optical','pagination_id',NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,'NO',NULL,1,NULL,'bigint','PRI','bigint(20)',NULL,19,0,NULL,'select,insert,update,references',1,NULL,NULL,''),
('papervote_optical','stack_id',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NO',NULL,1,NULL,'varchar','','varchar(32)',32,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,'');
INSERT  IGNORE INTO `ds_column_list_label` (`table_name`, `column_name`, `language`, `label`, `xtype`, `editor`, `position`, `summaryrenderer`, `renderer`, `summarytype`, `hidden`, `active`, `filterstore`, `grouped`, `flex`, `direction`, `align`, `listfiltertype`, `hint`) VALUES ('papervote_optical','ballotpaper_id','DE','Stimmzettel','gridcolumn',NULL,3,'','','',0,1,'',0,1.00,'ASC','left','',NULL),
('papervote_optical','box_id','DE','Kistencode','gridcolumn',NULL,0,'','','',0,1,'',0,1.00,'ASC','left','',NULL),
('papervote_optical','created','DE','Anlage','datecolumn',NULL,6,'','','',0,1,'',0,1.00,'ASC','left','',NULL),
('papervote_optical','marks','DE','Markierungen','gridcolumn',NULL,4,'','','',0,1,'',0,1.00,'ASC','left','',NULL),
('papervote_optical','modified','DE','Änderung','datecolumn',NULL,5,'','','',0,1,'',0,1.00,'ASC','left','',NULL),
('papervote_optical','pagination_id','DE','Pagination','gridcolumn',NULL,2,'','','',0,1,'',0,1.00,'ASC','left','',NULL),
('papervote_optical','stack_id','DE','Stapel','gridcolumn',NULL,1,'','','',0,1,'',0,1.00,'ASC','left','',NULL);
INSERT  IGNORE INTO `ds_column_form_label` (`table_name`, `column_name`, `language`, `label`, `xtype`, `field_path`, `position`, `hidden`, `active`, `allowempty`, `fieldgroup`, `flex`, `hint`) VALUES ('papervote_optical','ballotpaper_id','DE','Stimmzettel','displayfield','Allgemein/Angaben',3,1,0,0,'',0.00,'\'\''),
('papervote_optical','box_id','DE','Kistencode','displayfield','Allgemein/Angaben',0,1,0,0,'',0.00,'\'\''),
('papervote_optical','created','DE','Anlage','tualodatetimedisplayfield','Allgemein/Angaben',6,1,0,0,'',0.00,'\'\''),
('papervote_optical','marks','DE','Markierungen','displayfield','Allgemein/Angaben',4,1,0,0,'',0.00,'\'\''),
('papervote_optical','modified','DE','Änderung','tualodatetimedisplayfield','Allgemein/Angaben',5,1,0,0,'',0.00,'\'\''),
('papervote_optical','pagination_id','DE','Pagination','displayfield','Allgemein/Angaben',2,1,0,0,'',0.00,'\'\''),
('papervote_optical','stack_id','DE','Stapel','displayfield','Allgemein/Angaben',1,1,0,0,'',0.00,'\'\'');
INSERT  IGNORE INTO `ds_access` (`role`, `table_name`, `read`, `write`, `delete`, `append`, `existsreal`) VALUES ('administration','papervote_optical',1,1,NULL,NULL,NULL);
