DELIMITER ;

insert ignore into ds_pug_templates (name,id,note,template) values ('wm_berichte_tanboegen','wm_berichte_tanboegen',from_base64('d21fYmVyaWNodGVfdGFuYm9lZ2Vu'),from_base64( 'ZXh0ZW5kcyBibGdfc3RhbmRhcmRfdGVtcGxhdGVfbWFpbgpibG9jayBjb250ZW50CiAgICBlYWNo
IHJlY29yZCBpbiBkYXRhCiAgICAJaGVhZGVyKGNsYXNzPSJkZWJ1Z2JvcmRlciIsc3R5bGU9InRl
eHQtYWxpZ246bGVmdDsiKQogICAgICAgIAl0YWJsZShzdHlsZT0id2lkdGg6IDEwMCU7IikKICAg
ICAgICAgICAgCXRyCiAgICAgICAgICAgICAgICAJdGQoc3R5bGU9InRleHQtYWxpZ246bGVmdDsi
KQogICAgICAgICAgICAgICAgICAgIAlkc2ltYWdlKHRhYmxlbmFtZT0iZGF0ZWllbiIscXVlcnlm
aWVsZD0ibmFtZSIscXVlcnl2YWx1ZT0nbG9nbycsZmlsZWNvbHVtbj0iZGF0ZWkiLGhlaWdodD0i
MTAwJSIsc3R5bGU9ImhlaWdodDogMS41Y207IikKCiAgICAgICAgaDIgVGFuYm9nZW4gTnIuICF7
cmVjb3JkLmlkfQogICAgICAgIGRzKHRhYmxlbmFtZT0idGFubnVtbWVybiIsdGVtcGxhdGU9Indt
X2JlcmljaHRlX3RhbmJvZWdlbl90YWJlbGxlIikKCQkJZHNmaWx0ZXIocHJvcGVydHk9InRhbmJv
ZWdlbiIsb3BlcmF0b3I9ImVxIix2YWx1ZT1yZWNvcmQuaWQpCiAgICAgICAgICAgIGRzc29ydChw
cm9wZXJ0eT0iaWQiLGRpcmVjdGlvbj0iYXNjIikK') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('wm_berichte_tanboegen_tabelle','wm_berichte_tanboegen_tabelle',from_base64('d21fYmVyaWNodGVfdGFuYm9lZ2VuX3RhYmVsbGU='),from_base64( 'CnRhYmxlLmNhbmRpZGF0ZXRhYmxlCgl0cgogICAgCXRoLnJhbmsgTnIuCiAgICAJdGguYW56ZWln
ZV9uYW1lICZuYnNwOwogICAgLSB2YXIgbGFzdCA9IDEKCWVhY2ggcmVjb3JkIGluIGRhdGEKICAg
ICAgdHIudHJfbm90dm90ZWQKICAgICAgICB0ZC5yYW5rICF7cmVjb3JkLmlkfQogICAgICAgIHRk
CiAgICAgICAgCWJhcmNvZGVpbWFnZSh0eXBlPSJjMzkiLGRhdGE9cmVjb3JkLm5hbWUsInN0eWxl
Ij0id2lkdGg6NzBtbTtoZWlnaHQ6NW1tOyIpCiAgICAgIHRyLnRyX25vdHZvdGVkCiAgICAgICAg
dGQucmFuayAmbmJzcDsKICAgICAgICB0ZAogICAgICAgIAlzcGFuICF7cmVjb3JkLm5hbWV9CiAg
ICAgIHRyLnRyX25vdHZvdGVkCiAgICAgICAgdGQucmFuayAmbmJzcDsKICAgICAgICB0ZCAmbmJz
cDsKCQk=') );

insert ignore into ds_pug_templates (name,id,note,template) values ('wm_berichte_tanboegen_tabelle','wm_berichte_tanboegen_tabelle',from_base64('d21fYmVyaWNodGVfdGFuYm9lZ2VuX3RhYmVsbGU='),from_base64( 'CnRhYmxlLmNhbmRpZGF0ZXRhYmxlCgl0cgogICAgCXRoLnJhbmsgTnIuCiAgICAJdGguYW56ZWln
ZV9uYW1lICZuYnNwOwogICAgLSB2YXIgbGFzdCA9IDEKCWVhY2ggcmVjb3JkIGluIGRhdGEKICAg
ICAgdHIudHJfbm90dm90ZWQKICAgICAgICB0ZC5yYW5rICF7cmVjb3JkLmlkfQogICAgICAgIHRk
CiAgICAgICAgCWJhcmNvZGVpbWFnZSh0eXBlPSJjMzkiLGRhdGE9cmVjb3JkLm5hbWUsInN0eWxl
Ij0id2lkdGg6NzBtbTtoZWlnaHQ6NW1tOyIpCiAgICAgIHRyLnRyX25vdHZvdGVkCiAgICAgICAg
dGQucmFuayAmbmJzcDsKICAgICAgICB0ZAogICAgICAgIAlzcGFuICF7cmVjb3JkLm5hbWV9CiAg
ICAgIHRyLnRyX25vdHZvdGVkCiAgICAgICAgdGQucmFuayAmbmJzcDsKICAgICAgICB0ZCAmbmJz
cDsKCQk=') );

