DELIMITER ;
REPLACE INTO `ds` (`table_name`, `title`, `reorderfield`, `use_history`, `searchfield`, `displayfield`, `sortfield`, `searchany`, `hint`, `overview_tpl`, `sync_table`, `writetable`, `globalsearch`, `listselectionmodel`, `sync_view`, `syncable`, `cssstyle`, `alternativeformxtype`, `read_table`, `class_name`, `special_add_panel`, `existsreal`, `character_set_name`, `read_filter`, `listxtypeprefix`, `phpexporter`, `phpexporterfilename`, `combined`, `default_pagesize`, `allowForm`, `listviewbaseclass`, `showactionbtn`, `modelbaseclass`) VALUES ('stimmzettel','Stimmzettel','',0,'name','name','',1,'','','','',0,'cellmodel','',0,'','','','Wahlsystem','',1,'','','listview','XlsxWriter','stimmzettel',0,1000,0,'Tualo.DataSets.ListView',1,'Tualo.DataSets.model.Basic')
;
INSERT  IGNORE INTO `ds_column` (`table_name`, `column_name`, `default_value`, `default_max_value`, `default_min_value`, `update_value`, `is_primary`, `syncable`, `referenced_table`, `referenced_column_name`, `is_nullable`, `is_referenced`, `writeable`, `note`, `data_type`, `column_key`, `column_type`, `character_maximum_length`, `numeric_precision`, `numeric_scale`, `character_set_name`, `privileges`, `existsreal`, `deferedload`, `hint`, `fieldtype`) VALUES ('stimmzettel','aktiv','1',100000,0,'',0,0,'','','YES','NO',1,'','int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,0,'',''),
('stimmzettel','anzahl_10','0',100000,0,'',0,0,'','','YES','NO',1,'','int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,0,'',''),
('stimmzettel','anzahl_notwendige_bewerber_je_kombinummer','',0,0,'',0,0,'','','YES','NO',1,'','varchar','','varchar(255)',255,NULL,NULL,'utf8mb4','select,insert,update,references',1,0,'',''),
('stimmzettel','bh1','',10000000,0,NULL,0,0,NULL,NULL,'YES','NO',1,'','int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,0,'',''),
('stimmzettel','bh2','',10000000,0,NULL,0,0,NULL,NULL,'YES','NO',1,'','int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,0,'',''),
('stimmzettel','ds_count','0',0,0,'',0,0,'','','YES','NO',1,'','int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,0,'',''),
('stimmzettel','farbe','',10000000,0,'',0,0,'','','YES','NO',1,'','varchar','','varchar(100)',100,NULL,NULL,'utf8mb4','select,insert,update,references',1,0,'',''),
('stimmzettel','id','{#serial}',100000,1,'',1,0,'','','NO','NO',1,'','int','PRI','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,0,'',''),
('stimmzettel','insert_date','{DATE}',100000,0,'',0,0,'','','NO','NO',1,'','date','','date',NULL,NULL,NULL,NULL,'select,insert,update,references',1,0,'',''),
('stimmzettel','insert_time','{TIME}',100000,0,'',0,0,'','','YES','NO',1,'','time','','time',NULL,NULL,NULL,NULL,'select,insert,update,references',1,0,'',''),
('stimmzettel','kandidat_text_einzel','',10000000,0,NULL,0,0,NULL,NULL,'YES','NO',1,'','varchar','','varchar(50)',50,NULL,NULL,'utf8mb4','select,insert,update,references',1,0,'',''),
('stimmzettel','kandidat_text_mehr','',10000000,0,NULL,0,0,NULL,NULL,'YES','NO',1,'','varchar','','varchar(50)',50,NULL,NULL,'utf8mb4','select,insert,update,references',1,0,'',''),
('stimmzettel','laufende_nummer_1_24__nach_zuordnung_wg_wb','',0,0,'',0,0,'','','YES','NO',1,'','varchar','','varchar(255)',255,NULL,NULL,'utf8mb4','select,insert,update,references',1,0,'',''),
('stimmzettel','login','{:getSessionUser()}',100000,0,'null',0,0,'','','NO','NO',1,'','varchar','','varchar(255)',255,NULL,NULL,'utf8mb4','select,insert,update,references',1,0,'',''),
('stimmzettel','name','',100000,0,'',0,0,'','','YES','NO',1,'','varchar','','varchar(255)',255,NULL,NULL,'utf8mb4','select,insert,update,references',1,0,'',''),
('stimmzettel','ridx','{RIDX}',100000,0,'',0,0,'','','YES','NO',1,'','varchar','UNI','varchar(12)',12,NULL,NULL,'utf8mb4','select,insert,update,references',1,0,'',''),
('stimmzettel','sitzbindung','0',100000,0,'',0,0,'','','YES','NO',1,'','varchar','','varchar(255)',255,NULL,NULL,'utf8mb4','select,insert,update,references',1,0,'',''),
('stimmzettel','sitze','1',100000,0,'',0,0,'','','YES','NO',1,'','varchar','','varchar(255)',255,NULL,NULL,'utf8mb4','select,insert,update,references',1,0,'',''),
('stimmzettel','typtitel','',10000000,0,NULL,0,0,NULL,NULL,'YES','NO',1,'','varchar','','varchar(100)',100,NULL,NULL,'utf8mb4','select,insert,update,references',1,0,'',''),
('stimmzettel','ungueltig','',10000000,0,'',0,0,'','','YES','NO',1,'','int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,0,'',''),
('stimmzettel','update_date','{DATE}',100000,0,'null',0,0,'','','NO','NO',1,'','date','','date',NULL,NULL,NULL,NULL,'select,insert,update,references',1,0,'',''),
('stimmzettel','update_time','{TIME}',100000,0,'null',0,0,'','','YES','NO',1,'','time','','time',NULL,NULL,NULL,NULL,'select,insert,update,references',1,0,'',''),
('stimmzettel','wahlbezirk','',100000,0,'',0,0,'','','YES','NO',1,'','varchar','MUL','varchar(255)',255,NULL,NULL,'utf8mb4','select,insert,update,references',1,0,'',''),
('stimmzettel','wahlgruppe','',100000,0,'',0,0,'','','YES','NO',1,'','varchar','MUL','varchar(255)',255,NULL,NULL,'utf8mb4','select,insert,update,references',1,0,'',''),
('stimmzettel','wahltyp','',100000,0,'',0,0,'','','YES','NO',1,'','varchar','','varchar(255)',255,NULL,NULL,'utf8mb4','select,insert,update,references',1,0,'',''),
('stimmzettel','xlink','',10000000,0,NULL,0,0,NULL,NULL,'YES','NO',1,'','varchar','','varchar(255)',255,NULL,NULL,'utf8mb4','select,insert,update,references',1,0,'',''),
('stimmzettel','zaehlung_1','0',100000,0,'',0,0,'','','YES','NO',1,'','int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,0,'',''),
('stimmzettel','zaehlung_2','0',100000,0,'',0,0,'','','YES','NO',1,'','int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,0,'',''),
('stimmzettel','zaehlung_3','0',100000,0,'',0,0,'','','YES','NO',1,'','int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,0,'',''),
('stimmzettel','zaehlung_4','0',100000,0,'',0,0,'','','YES','NO',1,'','int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,0,'',''),
('stimmzettel','zaehlung_5','0',100000,0,'',0,0,'','','YES','NO',1,'','int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,0,'',''),
('stimmzettel','zaehlung_6','0',100000,0,'',0,0,'','','YES','NO',1,'','int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,0,'',''),
('stimmzettel','zaehlung_7','0',100000,0,'',0,0,'','','YES','NO',1,'','int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,0,'',''),
('stimmzettel','zaehlung_8','0',100000,0,'',0,0,'','','YES','NO',1,'','int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,0,'',''),
('stimmzettel','zaehlung_9','0',100000,0,'',0,0,'','','YES','NO',1,'','int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,0,'','');
INSERT  IGNORE INTO `ds_column_list_label` (`table_name`, `column_name`, `language`, `label`, `xtype`, `editor`, `position`, `summaryrenderer`, `renderer`, `summarytype`, `hidden`, `active`, `filterstore`, `grouped`, `flex`, `direction`, `align`, `listfiltertype`, `hint`) VALUES ('stimmzettel','aktiv','DE','Aktiv','gridcolumn','',1,'','','',1,1,'',0,1.00,'ASC','left','',''),
('stimmzettel','anzahl_10','DE','anzahl_10','gridcolumn','',15,'','','',1,0,'',0,1.00,'ASC','left','',''),
('stimmzettel','anzahl_notwendige_bewerber_je_kombinummer','DE','anzahl_notwendige_bewerber_je_kombinummer','gridcolumn','',23,'','','',1,0,'',0,1.00,'ASC','left','',''),
('stimmzettel','bh1','DE','Höhe 1','gridcolumn','',28,'','','',1,1,'',0,1.00,'','','',''),
('stimmzettel','bh2','DE','Höhe 2','gridcolumn','',29,'','','',1,1,'',0,1.00,'','','',''),
('stimmzettel','ds_count','DE','ds_count','gridcolumn','',18,'','','',1,0,'',0,1.00,'ASC','left','',''),
('stimmzettel','farbe','DE','Farbe','column_farben_rgb','',31,'','','',0,1,'',0,1.00,'','','',''),
('stimmzettel','id','DE','id','gridcolumn','',0,'','','',1,1,'',0,1.00,'ASC','left','',''),
('stimmzettel','insert_date','DE','insert_date','gridcolumn','',13,'','','',1,0,'',0,1.00,'ASC','left','',''),
('stimmzettel','insert_time','DE','insert_time','gridcolumn','',9,'','','',1,0,'',0,1.00,'ASC','left','',''),
('stimmzettel','kandidat_text_einzel','DE','kandidat_text_einzel','gridcolumn','',30,'','','',1,0,'',0,1.00,'','','',''),
('stimmzettel','kandidat_text_mehr','DE','kandidat_text_mehr','gridcolumn','',32,'','','',1,1,'',0,1.00,'','','',''),
('stimmzettel','laufende_nummer_1_24__nach_zuordnung_wg_wb','DE','laufende_nummer_1_24__nach_zuordnung_wg_wb','gridcolumn','',26,'','','',1,0,'',0,1.00,'ASC','left','',''),
('stimmzettel','login','DE','login','gridcolumn','',12,'','','',1,0,'',0,1.00,'ASC','left','',''),
('stimmzettel','name','DE','Name','gridcolumn','',2,'','','',0,1,'',0,1.00,'ASC','left','',''),
('stimmzettel','ridx','DE','ridx','gridcolumn','',27,'','','',1,0,'',0,1.00,'ASC','left','',''),
('stimmzettel','sitzbindung','DE','sitzbindung','gridcolumn','',22,'','','',1,0,'',0,1.00,'ASC','left','',''),
('stimmzettel','sitze','DE','sitze','gridcolumn','',10,'','','',1,0,'',0,1.00,'ASC','left','',''),
('stimmzettel','typtitel','DE','typtitel','gridcolumn','',33,'','','',0,1,'',0,1.00,'','','',''),
('stimmzettel','ungueltig','DE','Ungültig','tualocolumnnumber0','numberfield',6,'','','',0,1,'',0,1.00,'ASC','left','',''),
('stimmzettel','update_date','DE','update_date','gridcolumn','',21,'','','',1,0,'',0,1.00,'ASC','left','',''),
('stimmzettel','update_time','DE','update_time','gridcolumn','',17,'','','',1,0,'',0,1.00,'ASC','left','',''),
('stimmzettel','wahlbezirk','DE','Wahlbezirk','column_wahlbezirk_ridx','',4,'','','',1,1,'',0,1.00,'ASC','left','',''),
('stimmzettel','wahlgruppe','DE','Wahlgruppe','column_wahlgruppe_ridx','',3,'','','',1,1,'',0,1.00,'ASC','left','',''),
('stimmzettel','wahltyp','DE','Wahltyp','column_wahltyp_ridx','',5,'','','',0,1,'',0,1.00,'ASC','left','',''),
('stimmzettel','xlink','DE','xlink','gridcolumn','',999,'','','',1,1,'',0,1.00,'ASC','left','',''),
('stimmzettel','zaehlung_1','DE','zaehlung_1','gridcolumn','',8,'','','',1,0,'',0,1.00,'ASC','left','',''),
('stimmzettel','zaehlung_2','DE','zaehlung_2','gridcolumn','',24,'','','',1,0,'',0,1.00,'ASC','left','',''),
('stimmzettel','zaehlung_3','DE','zaehlung_3','gridcolumn','',11,'','','',1,0,'',0,1.00,'ASC','left','',''),
('stimmzettel','zaehlung_4','DE','zaehlung_4','gridcolumn','',16,'','','',1,0,'',0,1.00,'ASC','left','',''),
('stimmzettel','zaehlung_5','DE','zaehlung_5','gridcolumn','',25,'','','',1,0,'',0,1.00,'ASC','left','',''),
('stimmzettel','zaehlung_6','DE','zaehlung_6','gridcolumn','',20,'','','',1,0,'',0,1.00,'ASC','left','',''),
('stimmzettel','zaehlung_7','DE','zaehlung_7','gridcolumn','',7,'','','',1,0,'',0,1.00,'ASC','left','',''),
('stimmzettel','zaehlung_8','DE','zaehlung_8','gridcolumn','',14,'','','',1,0,'',0,1.00,'ASC','left','',''),
('stimmzettel','zaehlung_9','DE','zaehlung_9','gridcolumn','',19,'','','',1,0,'',0,1.00,'ASC','left','','');
INSERT  IGNORE INTO `ds_column_form_label` (`table_name`, `column_name`, `language`, `label`, `xtype`, `field_path`, `position`, `hidden`, `active`, `allowempty`, `fieldgroup`, `flex`, `hint`) VALUES ('stimmzettel','aktiv','DE','Aktiv','checkbox','Allgemein/Angaben',1,0,1,1,'',1.00,''),
('stimmzettel','anzahl_10','DE','Anzahl ohne Wahlschein','numberfield','Zählung/Angaben',20,0,1,1,'',1.00,''),
('stimmzettel','anzahl_notwendige_bewerber_je_kombinummer','DE','anzahl_notwendige_bewerber_je_kombinummer','displayfield','Allgemein',32,1,0,0,'',1.00,''),
('stimmzettel','bh1','DE','Höhe 1','numberfield','Allgemein/Angaben',9,0,1,1,'',1.00,''),
('stimmzettel','bh2','DE','Höhe 2','numberfield','Allgemein/Angaben',10,0,1,1,'',1.00,''),
('stimmzettel','ds_count','DE','ds_count','displayfield','Allgemein',30,1,0,0,'',1.00,''),
('stimmzettel','farbe','DE','Farbe','combobox_farben_rgb','Allgemein/Angaben',7,0,1,0,'',1.00,''),
('stimmzettel','id','DE','ID','displayfield','Allgemein/Satzinformationen',15,0,1,1,'',1.00,''),
('stimmzettel','insert_date','DE','Anlagedatum','displayfield','Allgemein/Satzinformationen',17,0,1,1,'',1.00,''),
('stimmzettel','insert_time','DE','Anlagezeit','displayfield','Allgemein/Satzinformationen',14,0,1,1,'',1.00,''),
('stimmzettel','kandidat_text_einzel','DE','kandidat_text_einzel','displayfield','Allgemein',34,1,0,0,'',1.00,''),
('stimmzettel','kandidat_text_mehr','DE','Kand. Texttyp','textfield','Allgemein/Angaben',8,0,1,1,'',1.00,''),
('stimmzettel','laufende_nummer_1_24__nach_zuordnung_wg_wb','DE','laufende_nummer_1_24__nach_zuordnung_wg_wb','displayfield','Allgemein',33,1,0,0,'',1.00,''),
('stimmzettel','login','DE','Login','displayfield','Allgemein/Satzinformationen',19,0,1,1,'',1.00,''),
('stimmzettel','name','DE','Name','textfield','Allgemein/Angaben',0,0,1,1,'',1.00,''),
('stimmzettel','ridx','DE','RIDX','displayfield','Allgemein/Satzinformationen',16,0,1,1,'',1.00,''),
('stimmzettel','sitzbindung','DE','Sitzbindung','numberfield','Allgemein/Angaben',6,0,1,1,'',1.00,''),
('stimmzettel','sitze','DE','Sitze','numberfield','Allgemein/Angaben',5,0,1,1,'',1.00,''),
('stimmzettel','typtitel','DE','Typtitel','textarea','Allgemein/Angaben',12,0,1,1,'',1.00,''),
('stimmzettel','ungueltig','DE','ungueltig','displayfield','Allgemein',31,1,0,0,'',1.00,''),
('stimmzettel','update_date','DE','Änderungsdatum','displayfield','Allgemein/Satzinformationen',18,0,1,1,'',1.00,''),
('stimmzettel','update_time','DE','Änderungszeit','displayfield','Allgemein/Satzinformationen',13,0,1,1,'',1.00,''),
('stimmzettel','wahlbezirk','DE','Wahlbezirk','combobox_wahlbezirk_ridx','Allgemein/Angaben',3,0,1,1,'',1.00,''),
('stimmzettel','wahlgruppe','DE','Wahlgruppe','combobox_wahlgruppe_ridx','Allgemein/Angaben',2,0,1,1,'',1.00,''),
('stimmzettel','wahltyp','DE','Wahltyp','combobox_wahltyp_ridx','Allgemein/Angaben',4,0,1,1,'',1.00,''),
('stimmzettel','xlink','DE','X-Link','textfield','Allgemein/Angaben',11,0,1,1,'',1.00,''),
('stimmzettel','zaehlung_1','DE','Anzahl Umschlag: ohne Stimmzettel','numberfield','Zählung/Angaben',21,0,1,1,'',1.00,''),
('stimmzettel','zaehlung_2','DE','Anzahl Umschlag: mit mehr als einem Stimmzettel','numberfield','Zählung/Angaben',22,0,1,1,'',1.00,''),
('stimmzettel','zaehlung_3','DE','Anzahl Umschlag: mit fremden Inhalt','numberfield','Zählung/Angaben',23,0,1,1,'',1.00,''),
('stimmzettel','zaehlung_4','DE','Anzahl Umschlag: mit Stimmzettel mit Enthaltung','numberfield','Zählung/Angaben',24,0,1,1,'',1.00,''),
('stimmzettel','zaehlung_5','DE','Anzahl Umschlag: mit beschaedigtem Stimmzettel','numberfield','Zählung/Angaben',25,0,1,1,'',1.00,''),
('stimmzettel','zaehlung_6','DE','Anzahl Stimmzettel mit Enthaltung','numberfield','Zählung/Angaben',26,0,1,1,'',1.00,''),
('stimmzettel','zaehlung_7','DE','Anzahl Stimmzettel mit Streichungen/ Vermerken','numberfield','Zählung/Angaben',27,0,1,1,'',1.00,''),
('stimmzettel','zaehlung_8','DE','Anzahl Stimmzettel mit mehr Kreuzen','numberfield','Zählung/Angaben',28,0,1,1,'',1.00,''),
('stimmzettel','zaehlung_9','DE','Anzahl Umschlag: SZ mit mehr Kreuzen','numberfield','Zählung/Angaben',29,0,1,1,'',1.00,'');
INSERT  IGNORE INTO `ds_dropdownfields` (`table_name`, `name`, `idfield`, `displayfield`, `filterconfig`) VALUES ('stimmzettel','RIDX','ridx','name','');
INSERT  IGNORE INTO `ds_reference_tables` (`table_name`, `reference_table_name`, `columnsdef`, `constraint_name`, `active`, `searchable`, `autosync`, `position`, `path`, `existsreal`, `tabtitle`) VALUES ('stimmzettel','stimmzettelgruppen','{\"stimmzettel__stimmzettelgruppen\":\"stimmzettelgruppen__name\"}','fk_stimmzettel_stimmzettelgruppen',0,0,1,99999,'',0,''),
('stimmzettel','wahlbezirk','{\"wahlbezirk\":\"ridx\"}','fk_stimmzettel_wahlbezirk',0,0,0,999,'',1,''),
('stimmzettel','wahlgruppe','{\"wahlgruppe\":\"ridx\"}','fk_stimmzettel_wahlgruppe',0,0,0,999,'',1,'');
INSERT  IGNORE INTO `ds_access` (`role`, `table_name`, `read`, `write`, `delete`, `append`, `existsreal`) VALUES ('administration','stimmzettel',1,1,1,1,1);
