DELIMITER ;
INSERT INTO `ds` (`table_name`, `title`, `reorderfield`, `use_history`, `searchfield`, `displayfield`, `sortfield`, `searchany`, `hint`, `overview_tpl`, `sync_table`, `writetable`, `globalsearch`, `listselectionmodel`, `sync_view`, `syncable`, `cssstyle`, `read_table`, `existsreal`, `class_name`, `special_add_panel`, `read_filter`, `listxtypeprefix`, `phpexporter`, `phpexporterfilename`, `combined`, `allowForm`, `alternativeformxtype`, `character_set_name`, `default_pagesize`, `listviewbaseclass`, `showactionbtn`) VALUES ('view_stimmenanzahl_ranking_los','Ranking-Stimmenverteilung','',0,'anzeige_name','anzeige_name','rank',1,'','','','',0,'tualomultirowmodel','',0,'','',1,'Wahlsystem','','','listview','XlsxWriter','{GUID}',0,0,'','',100,'Tualo.DataSets.ListView',1) ON DUPLICATE KEY UPDATE title=VALUES(title), reorderfield=VALUES(reorderfield), use_history=VALUES(use_history), searchfield=VALUES(searchfield), displayfield=VALUES(displayfield), sortfield=VALUES(sortfield), searchany=VALUES(searchany), hint=VALUES(hint), overview_tpl=VALUES(overview_tpl), sync_table=VALUES(sync_table), writetable=VALUES(writetable), globalsearch=VALUES(globalsearch), listselectionmodel=VALUES(listselectionmodel), sync_view=VALUES(sync_view), syncable=VALUES(syncable), cssstyle=VALUES(cssstyle), alternativeformxtype=VALUES(alternativeformxtype), read_table=   VALUES(read_table), class_name=VALUES(class_name), special_add_panel=VALUES(special_add_panel), existsreal=VALUES(existsreal), character_set_name=VALUES(character_set_name), read_filter=VALUES(read_filter), listxtypeprefix=VALUES(listxtypeprefix), phpexporter=VALUES(phpexporter), phpexporterfilename=VALUES(phpexporterfilename), combined=VALUES(combined), default_pagesize=VALUES(default_pagesize), allowForm=VALUES(allowForm), listviewbaseclass=VALUES(listviewbaseclass), showactionbtn=VALUES(showactionbtn), modelbaseclass=VALUES(modelbaseclass);
INSERT  IGNORE INTO `ds_column` (`table_name`, `column_name`, `default_value`, `default_max_value`, `default_min_value`, `is_primary`, `update_value`, `is_nullable`, `is_referenced`, `referenced_table`, `referenced_column_name`, `data_type`, `column_key`, `column_type`, `character_maximum_length`, `numeric_precision`, `numeric_scale`, `character_set_name`, `privileges`, `existsreal`, `deferedload`, `writeable`, `note`, `hint`) VALUES ('view_stimmenanzahl_ranking_los','anzeige_name','',10000000,0,0,'','YES','NO','','','text','','text',65535,NULL,NULL,'utf8mb3','select,insert,update,references',1,0,1,'',''),
('view_stimmenanzahl_ranking_los','barcode','',10000000,0,0,'','YES','NO','','','varchar','','varchar(5)',5,NULL,NULL,'utf8mb3','select,insert,update,references',1,0,1,'',''),
('view_stimmenanzahl_ranking_los','dense_rank','',10000000,0,0,'','NO','NO','','','bigint','','bigint(21)',NULL,19,0,NULL,'select,insert,update,references',1,0,1,'',''),
('view_stimmenanzahl_ranking_los','gewaehlt','',10000000,0,0,'','YES','NO','','','tinyint','','int(1)',NULL,10,0,NULL,'select,insert,update,references',1,0,1,'',''),
('view_stimmenanzahl_ranking_los','gezaehlte_stimmzettel','',10000000,0,0,NULL,'NO','NO',NULL,NULL,'decimal','','decimal(42,0)',NULL,42,0,NULL,'select,insert,update,references',1,0,1,'',''),
('view_stimmenanzahl_ranking_los','id','',10000000,0,0,NULL,'NO','NO',NULL,NULL,'int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,0,1,'',''),
('view_stimmenanzahl_ranking_los','json_candidate','',10000000,0,0,NULL,'YES','NO',NULL,NULL,'longtext','','longtext',4294967295,NULL,NULL,'utf8mb3','select,insert,update,references',1,0,1,'',''),
('view_stimmenanzahl_ranking_los','kiste2','',10000000,0,0,'','YES','NO','','','mediumtext','','mediumtext',16777215,NULL,NULL,'utf8mb3','select,insert,update,references',1,0,1,'',''),
('view_stimmenanzahl_ranking_los','listenplatz','',10000000,0,0,NULL,'NO','NO',NULL,NULL,'bigint','','bigint(21)',NULL,19,0,NULL,'select,insert,update,references',1,0,1,'',''),
('view_stimmenanzahl_ranking_los','nachruecker','',10000000,0,0,NULL,'YES','NO',NULL,NULL,'tinyint','','tinyint(4)',NULL,3,0,NULL,'select,insert,update,references',1,0,1,'',''),
('view_stimmenanzahl_ranking_los','offline','',10000000,0,0,'','NO','NO','','','bigint','','bigint(21)',NULL,19,0,NULL,'select,insert,update,references',1,0,1,'',''),
('view_stimmenanzahl_ranking_los','online','',10000000,0,0,'','NO','NO','','','int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,0,1,'',''),
('view_stimmenanzahl_ranking_los','rank','',10000000,0,0,'','NO','NO','','','bigint','','bigint(21)',NULL,19,0,NULL,'select,insert,update,references',1,0,1,'',''),
('view_stimmenanzahl_ranking_los','row_num','',10000000,0,0,'','NO','NO','','','bigint','','bigint(21)',NULL,19,0,NULL,'select,insert,update,references',1,0,1,'',''),
('view_stimmenanzahl_ranking_los','sitze','',10000000,0,0,'','YES','NO','','','int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,0,1,'',''),
('view_stimmenanzahl_ranking_los','stapel2','',10000000,0,0,'','YES','NO','','','mediumtext','','mediumtext',16777215,NULL,NULL,'utf8mb3','select,insert,update,references',1,0,1,'',''),
('view_stimmenanzahl_ranking_los','stimmenanzahl','',10000000,0,0,'','NO','NO','','','bigint','','bigint(22)',NULL,19,0,NULL,'select,insert,update,references',1,0,1,'',''),
('view_stimmenanzahl_ranking_los','stimmzettelanzahl','',10000000,0,0,'','NO','NO','','','bigint','','bigint(21)',NULL,19,0,NULL,'select,insert,update,references',1,0,1,'',''),
('view_stimmenanzahl_ranking_los','stimmzettelgruppen_name','',10000000,0,0,'','YES','NO','','','varchar','','varchar(255)',255,NULL,NULL,'utf8mb3','select,insert,update,references',1,0,1,'',''),
('view_stimmenanzahl_ranking_los','stimmzettelgruppen_ridx','',10000000,0,0,'','YES','NO','','','varchar','','varchar(12)',12,NULL,NULL,'utf8mb3','select,insert,update,references',1,0,1,'',''),
('view_stimmenanzahl_ranking_los','stimmzettel_name','',10000000,0,0,'','YES','NO','','','varchar','','varchar(255)',255,NULL,NULL,'utf8mb3','select,insert,update,references',1,0,1,'',''),
('view_stimmenanzahl_ranking_los','stimmzettel_ridx','',10000000,0,0,'','YES','NO','','','varchar','','varchar(12)',12,NULL,NULL,'utf8mb3','select,insert,update,references',1,0,1,'','');
INSERT  IGNORE INTO `ds_column_list_label` (`table_name`, `column_name`, `language`, `label`, `xtype`, `editor`, `position`, `summaryrenderer`, `summarytype`, `hidden`, `active`, `renderer`, `filterstore`, `flex`, `direction`, `align`, `grouped`, `listfiltertype`, `hint`) VALUES ('view_stimmenanzahl_ranking_los','anzeige_name','DE','Anzeigename','gridcolumn','',1,'','',0,1,'','',1.00,'ASC','left',0,'',''),
('view_stimmenanzahl_ranking_los','barcode','DE','Barcode','gridcolumn','',0,'','',0,1,'','',1.00,'ASC','left',0,'',''),
('view_stimmenanzahl_ranking_los','dense_rank','DE','Dense-Rank','gridcolumn','',9,'','',1,1,'','',1.00,'ASC','left',0,'',''),
('view_stimmenanzahl_ranking_los','gewaehlt','DE','ist gewählt','gridcolumn','',5,'','',0,1,'','',1.00,'ASC','left',0,'',''),
('view_stimmenanzahl_ranking_los','kiste2','DE','Kiste','gridcolumn','',12,'','',1,1,'','',1.00,'ASC','left',0,'',''),
('view_stimmenanzahl_ranking_los','offline','DE','Offline-Stimmen','gridcolumn','',6,'','',0,1,'','',1.00,'ASC','left',0,'',''),
('view_stimmenanzahl_ranking_los','online','DE','Online-Stimmen','gridcolumn','',7,'','',0,1,'','',1.00,'ASC','left',0,'',''),
('view_stimmenanzahl_ranking_los','rank','DE','Platzierung','gridcolumn','',2,'','',0,1,'','',1.00,'ASC','left',0,'',''),
('view_stimmenanzahl_ranking_los','row_num','DE','Reihenfolge','gridcolumn','',14,'','',1,1,'','',1.00,'ASC','left',0,'',''),
('view_stimmenanzahl_ranking_los','sitze','DE','Sitze','gridcolumn','',10,'','',0,1,'','',1.00,'ASC','left',0,'',''),
('view_stimmenanzahl_ranking_los','stapel2','DE','Stapel','gridcolumn','',13,'','',1,1,'','',1.00,'ASC','left',0,'',''),
('view_stimmenanzahl_ranking_los','stimmenanzahl','DE','Stimmenanzahl','gridcolumn','',8,'','',0,1,'','',1.00,'ASC','left',0,'',''),
('view_stimmenanzahl_ranking_los','stimmzettelanzahl','DE','Stimmzettelanzahl (Briefwahl)','gridcolumn','',11,'','',0,1,'','',1.00,'ASC','left',0,'',''),
('view_stimmenanzahl_ranking_los','stimmzettelgruppen_name','DE','Stimmzettelgruppe','gridcolumn','',4,'','',0,1,'','',1.00,'ASC','left',0,'',''),
('view_stimmenanzahl_ranking_los','stimmzettelgruppen_ridx','DE','Stimmzettelgruppen (RIDX)','gridcolumn','',15,'','',1,1,'','',1.00,'ASC','left',0,'',''),
('view_stimmenanzahl_ranking_los','stimmzettel_name','DE','Stimmzettel','gridcolumn','',3,'','',0,1,'','',1.00,'ASC','left',0,'',''),
('view_stimmenanzahl_ranking_los','stimmzettel_ridx','DE','Stimmzettel (RIDX)','gridcolumn','',16,'','',1,1,'','',1.00,'ASC','left',0,'','');
INSERT  IGNORE INTO `ds_column_form_label` (`table_name`, `column_name`, `language`, `label`, `xtype`, `field_path`, `position`, `hidden`, `active`, `allowempty`, `fieldgroup`) VALUES ('view_stimmenanzahl_ranking_los','anzeige_name','DE','Anzeigename','displayfield','Allgemein/Angaben',1,0,1,1,''),
('view_stimmenanzahl_ranking_los','barcode','DE','Barcode','displayfield','Allgemein/Angaben',0,0,1,1,''),
('view_stimmenanzahl_ranking_los','dense_rank','DE','Dense-Rank','displayfield','Allgemein/Angaben',9,0,1,1,''),
('view_stimmenanzahl_ranking_los','gewaehlt','DE','ist gewählt','displayfield','Allgemein/Angaben',5,0,1,1,''),
('view_stimmenanzahl_ranking_los','kiste2','DE','Kiste','displayfield','Allgemein/Angaben',12,0,1,1,''),
('view_stimmenanzahl_ranking_los','offline','DE','Offline-Stimmen','displayfield','Allgemein/Angaben',6,0,1,1,''),
('view_stimmenanzahl_ranking_los','online','DE','Online-Stimmen','displayfield','Allgemein/Angaben',7,0,1,1,''),
('view_stimmenanzahl_ranking_los','rank','DE','Platzierung','displayfield','Allgemein/Angaben',2,0,1,1,''),
('view_stimmenanzahl_ranking_los','row_num','DE','Reihenfolge','displayfield','Allgemein/Angaben',14,0,1,1,''),
('view_stimmenanzahl_ranking_los','sitze','DE','Sitze','displayfield','Allgemein/Angaben',10,0,1,1,''),
('view_stimmenanzahl_ranking_los','stapel2','DE','Stapel','displayfield','Allgemein/Angaben',13,0,1,1,''),
('view_stimmenanzahl_ranking_los','stimmenanzahl','DE','Stimmenanzahl','displayfield','Allgemein/Angaben',8,0,1,1,''),
('view_stimmenanzahl_ranking_los','stimmzettelanzahl','DE','Stimmzettelanzahl (Briefwahl)','displayfield','Allgemein/Angaben',11,0,1,1,''),
('view_stimmenanzahl_ranking_los','stimmzettelgruppen_name','DE','Stimmzettelgruppe','displayfield','Allgemein/Angaben',4,0,1,1,''),
('view_stimmenanzahl_ranking_los','stimmzettelgruppen_ridx','DE','Stimmzettelgruppen (RIDX)','displayfield','Allgemein/Angaben',15,0,1,1,''),
('view_stimmenanzahl_ranking_los','stimmzettel_name','DE','Stimmzettel','displayfield','Allgemein/Angaben',3,0,1,1,''),
('view_stimmenanzahl_ranking_los','stimmzettel_ridx','DE','Stimmzettel (RIDX)','displayfield','Allgemein/Angaben',16,0,1,1,'');
INSERT  IGNORE INTO `ds_access` (`role`, `table_name`, `read`, `write`, `delete`, `append`, `existsreal`) VALUES ('_default_','view_stimmenanzahl_ranking_los',1,0,0,0,1);


update `ds_column` set `is_primary`=1 where 
`table_name`='view_stimmenanzahl_ranking_los' and `column_name`='id'
and (select sum(`is_primary`) from `ds_column` where `table_name`='view_stimmenanzahl_ranking_los')=0;
