DELIMITER ;
INSERT INTO `ds` (`table_name`, `title`, `reorderfield`, `use_history`, `searchfield`, `displayfield`, `sortfield`, `searchany`, `hint`, `overview_tpl`, `sync_table`, `writetable`, `globalsearch`, `listselectionmodel`, `sync_view`, `syncable`, `cssstyle`, `alternativeformxtype`, `read_table`, `class_name`, `special_add_panel`, `existsreal`, `character_set_name`, `read_filter`, `listxtypeprefix`, `phpexporter`, `phpexporterfilename`, `combined`, `default_pagesize`, `allowForm`, `listviewbaseclass`, `showactionbtn`, `modelbaseclass`) VALUES ('wahlberechtigte','Wahlberechtigte','',0,'identnummer','identnummer','id',1,'','','','',0,'','',0,'','','','Wahlsystem','',1,'','','listview','XlsxWriter','wahlberechtigte',0,10000,0,'Tualo.DataSets.ListView',1,'Tualo.DataSets.model.Basic') ON DUPLICATE KEY UPDATE title=VALUES(title), reorderfield=VALUES(reorderfield), use_history=VALUES(use_history), searchfield=VALUES(searchfield), displayfield=VALUES(displayfield), sortfield=VALUES(sortfield), searchany=VALUES(searchany), hint=VALUES(hint), overview_tpl=VALUES(overview_tpl), sync_table=VALUES(sync_table), writetable=VALUES(writetable), globalsearch=VALUES(globalsearch), listselectionmodel=VALUES(listselectionmodel), sync_view=VALUES(sync_view), syncable=VALUES(syncable), cssstyle=VALUES(cssstyle), alternativeformxtype=VALUES(alternativeformxtype), read_table=   VALUES(read_table), class_name=VALUES(class_name), special_add_panel=VALUES(special_add_panel), existsreal=VALUES(existsreal), character_set_name=VALUES(character_set_name), read_filter=VALUES(read_filter), listxtypeprefix=VALUES(listxtypeprefix), phpexporter=VALUES(phpexporter), phpexporterfilename=VALUES(phpexporterfilename), combined=VALUES(combined), default_pagesize=VALUES(default_pagesize), allowForm=VALUES(allowForm), listviewbaseclass=VALUES(listviewbaseclass), showactionbtn=VALUES(showactionbtn), modelbaseclass=VALUES(modelbaseclass);
REPLACE INTO `ds_column` (`table_name`, `column_name`, `default_value`, `default_max_value`, `default_min_value`, `update_value`, `is_primary`, `syncable`, `referenced_table`, `referenced_column_name`, `is_nullable`, `is_referenced`, `writeable`, `note`, `data_type`, `column_key`, `column_type`, `character_maximum_length`, `numeric_precision`, `numeric_scale`, `character_set_name`, `privileges`, `existsreal`, `deferedload`, `hint`, `fieldtype`) VALUES ('wahlberechtigte','aktiv','',100000,0,'',0,0,NULL,NULL,'YES','NO',1,'','varchar','','varchar(255)',255,NULL,NULL,'utf8mb4','select,insert,update,references',1,0,'',''),
('wahlberechtigte','id','',0,0,'',1,0,NULL,NULL,'NO','NO',1,'','bigint','PRI','bigint(20)',NULL,19,0,NULL,'select,insert,update,references',1,0,'',''),
('wahlberechtigte','identkurz','',100000,0,'',0,0,NULL,NULL,'YES','NO',1,'','int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,0,'',''),
('wahlberechtigte','identnummer','',100000,0,'',0,0,NULL,NULL,'YES','NO',1,'','varchar','MUL','varchar(255)',255,NULL,NULL,'utf8mb4','select,insert,update,references',1,0,'',''),
('wahlberechtigte','insert_date','{DATE}',100000,0,'',0,0,'','','YES','NO',1,'','date','','date',0,0,0,'','select,insert,update,references',1,0,'',''),
('wahlberechtigte','insert_time','{TIME}',100000,0,'',0,0,'','','YES','NO',1,'','time','','time',0,0,0,'','select,insert,update,references',1,0,'',''),
('wahlberechtigte','kostenstelle','0',0,0,'',1,0,NULL,NULL,'NO','NO',1,'','int','PRI','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,0,'',''),
('wahlberechtigte','login','{:getSessionUser()}',100000,0,'',0,0,'','','YES','NO',1,'','varchar','','varchar(255)',255,0,0,'utf8mb4','select,insert,update,references',1,0,'',''),
('wahlberechtigte','ridx','',100000,0,'',0,0,NULL,NULL,'YES','NO',1,'','varchar','UNI','varchar(12)',12,NULL,NULL,'utf8mb4','select,insert,update,references',1,0,'',''),
('wahlberechtigte','update_date','{DATE}',100000,0,'null',0,0,'','','YES','NO',1,'','date','','date',0,0,0,'','select,insert,update,references',1,0,'',''),
('wahlberechtigte','update_time','{TIME}',100000,0,'null',0,0,'','','YES','NO',1,'','time','','time',0,0,0,'','select,insert,update,references',1,0,'','');
INSERT  IGNORE INTO `ds_column_list_label` (`table_name`, `column_name`, `language`, `label`, `xtype`, `editor`, `position`, `summaryrenderer`, `renderer`, `summarytype`, `hidden`, `active`, `filterstore`, `grouped`, `flex`, `direction`, `align`, `listfiltertype`, `hint`) VALUES ('wahlberechtigte','aktiv','DE','Aktiv','gridcolumn','',1,'','','',0,1,'',0,1.00,'ASC','left','',''),
('wahlberechtigte','id','DE','ID','gridcolumn','',18,'','','',0,1,'',0,1.00,'ASC','left','',''),
('wahlberechtigte','identkurz','DE','identkurz','gridcolumn','',11,'','','',0,1,'',0,1.00,'ASC','left','',''),
('wahlberechtigte','identnummer','DE','Identnummer','gridcolumn','',2,'','','',0,1,'',0,1.00,'ASC','left','',''),
('wahlberechtigte','insert_date','DE','Anlagedatum','gridcolumn','',16,'','','',0,1,'',0,1.00,'ASC','left','',''),
('wahlberechtigte','insert_time','DE','Anlagezeit','gridcolumn','',15,'','','',0,1,'',0,1.00,'ASC','left','',''),
('wahlberechtigte','kostenstelle','DE','kostenstelle','gridcolumn','',0,'','','',0,1,'',0,1.00,'ASC','left','',''),
('wahlberechtigte','land','DE','Land','gridcolumn','',10,'','','',0,1,'',0,1.00,'ASC','left','',''),
('wahlberechtigte','login','DE','Login','gridcolumn','',13,'','','',0,1,'',0,1.00,'ASC','left','',''),
('wahlberechtigte','name','DE','Name','gridcolumn','',3,'','','',0,1,'',0,1.00,'ASC','left','',''),
('wahlberechtigte','name2','DE','Name2','gridcolumn','',4,'','','',0,1,'',0,1.00,'ASC','left','',''),
('wahlberechtigte','name3','DE','Name3','gridcolumn','',5,'','','',0,1,'',0,1.00,'ASC','left','',''),
('wahlberechtigte','name4','DE','Name4','gridcolumn','',6,'','','',0,1,'',0,1.00,'ASC','left','',''),
('wahlberechtigte','ort','DE','Ort','gridcolumn','',9,'','','',0,1,'',0,1.00,'ASC','left','',''),
('wahlberechtigte','plz','DE','PLZ','gridcolumn','',8,'','','',0,1,'',0,1.00,'ASC','left','',''),
('wahlberechtigte','ridx','DE','RIDX','gridcolumn','',14,'','','',0,1,'',0,1.00,'ASC','left','',''),
('wahlberechtigte','str','DE','Strasse','gridcolumn','',7,'','','',0,1,'',0,1.00,'ASC','left','',''),
('wahlberechtigte','update_date','DE','Änderungsdatum','gridcolumn','',17,'','','',0,1,'',0,1.00,'ASC','left','',''),
('wahlberechtigte','update_time','DE','Änderungszeit','gridcolumn','',12,'','','',0,1,'',0,1.00,'ASC','left','','');
INSERT  IGNORE INTO `ds_column_form_label` (`table_name`, `column_name`, `language`, `label`, `xtype`, `field_path`, `position`, `hidden`, `active`, `allowempty`, `fieldgroup`, `flex`, `hint`) VALUES ('wahlberechtigte','aktiv','DE','Aktiv','textfield','Allgemein',1,0,1,1,'',1.00,''),
('wahlberechtigte','id','DE','id','displayfield','Allgemein',0,0,1,1,'',1.00,''),
('wahlberechtigte','identkurz','DE','identkurz','textfield','Allgemein',11,0,1,1,'',1.00,''),
('wahlberechtigte','identnummer','DE','Identnummer','textfield','Allgemein',2,0,1,1,'',1.00,''),
('wahlberechtigte','insert_date','DE','Anlagedatum','textfield','Allgemein',16,0,1,1,'',1.00,''),
('wahlberechtigte','insert_time','DE','Anlagezeit','textfield','Allgemein',15,0,1,1,'',1.00,''),
('wahlberechtigte','kostenstelle','DE','kostenstelle','displayfield','Allgemein',0,0,1,1,'',1.00,''),
('wahlberechtigte','land','DE','Land','textfield','Allgemein',10,0,1,1,'',1.00,''),
('wahlberechtigte','login','DE','Login','textfield','Allgemein',13,0,1,1,'',1.00,''),
('wahlberechtigte','name','DE','Name','textfield','Allgemein',3,0,1,1,'',1.00,''),
('wahlberechtigte','name2','DE','Name2','textfield','Allgemein',4,0,1,1,'',1.00,''),
('wahlberechtigte','name3','DE','Name3','textfield','Allgemein',5,0,1,1,'',1.00,''),
('wahlberechtigte','name4','DE','Name4','textfield','Allgemein',6,0,1,1,'',1.00,''),
('wahlberechtigte','ort','DE','Ort','textfield','Allgemein',9,0,1,1,'',1.00,''),
('wahlberechtigte','plz','DE','PLZ','textfield','Allgemein',8,0,1,1,'',1.00,''),
('wahlberechtigte','ridx','DE','RIDX','textfield','Allgemein',14,0,1,1,'',1.00,''),
('wahlberechtigte','str','DE','Strasse','textfield','Allgemein',7,0,1,1,'',1.00,''),
('wahlberechtigte','update_date','DE','Änderungsdatum','textfield','Allgemein',17,0,1,1,'',1.00,''),
('wahlberechtigte','update_time','DE','Änderungszeit','textfield','Allgemein',12,0,1,1,'',1.00,'');
INSERT  IGNORE INTO `ds_dropdownfields` (`table_name`, `name`, `idfield`, `displayfield`, `filterconfig`) VALUES ('wahlberechtigte','RIDX','ridx','name',NULL);
INSERT  IGNORE INTO `ds_access` (`role`, `table_name`, `read`, `write`, `delete`, `append`, `existsreal`) VALUES ('administration','wahlberechtigte',1,1,1,1,1);
