DELIMITER ;
insert ignore into ds_pug_templates (name,id,note,template) values ('wm_berichte_tanboegen','wm_berichte_tanboegen',from_base64('d21fYmVyaWNodGVfdGFuYm9lZ2Vu'),from_base64( 'ZXh0ZW5kcyB3bV9iZXJpY2h0ZV93cmFwcGVyCmJsb2NrIGNvbnRlbnQKICAgIGVhY2ggcmVjb3Jk
IGluIGRhdGEKICAgIAloZWFkZXIoY2xhc3M9ImRlYnVnYm9yZGVyIixzdHlsZT0idGV4dC1hbGln
bjpsZWZ0OyIpCiAgICAgICAgCXRhYmxlKHN0eWxlPSJ3aWR0aDogMTAwJTsiKQogICAgICAgICAg
ICAJdHIKICAgICAgICAgICAgICAgIAl0ZChzdHlsZT0idGV4dC1hbGlnbjpsZWZ0OyIpCiAgICAg
ICAgICAgICAgICAgICAgCWRzaW1hZ2UodGFibGVuYW1lPSJkYXRlaWVuIixxdWVyeWZpZWxkPSJu
YW1lIixxdWVyeXZhbHVlPSdsb2dvJyxmaWxlY29sdW1uPSJkYXRlaSIsaGVpZ2h0PSIxMDAlIixz
dHlsZT0iaGVpZ2h0OiAxLjVjbTsiKQoKICAgICAgICBoMiBUYW5ib2dlbiBOci4gIXtyZWNvcmQu
aWR9CiAgICAgICAgZHModGFibGVuYW1lPSJ3bV90YW5udW1tZXIiLHRlbXBsYXRlPSJ3bV9iZXJp
Y2h0ZV90YW5ib2VnZW5fdGFiZWxsZSIpCgkJCWRzZmlsdGVyKHByb3BlcnR5PSJ0YW5ib2VnZW4i
LG9wZXJhdG9yPSJlcSIsdmFsdWU9cmVjb3JkLmlkKQogICAgICAgICAgICBkc3NvcnQocHJvcGVy
dHk9InRhbm51bW1lciIsZGlyZWN0aW9uPSJhc2MiKQo=') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('wm_berichte_tanboegen_tabelle','wm_berichte_tanboegen_tabelle',from_base64('d21fYmVyaWNodGVfdGFuYm9lZ2VuX3RhYmVsbGU='),from_base64( 'CnRhYmxlLmNhbmRpZGF0ZXRhYmxlCgl0cgogICAgCXRoLnJhbmsgTnIuCiAgICAJdGguYW56ZWln
ZV9uYW1lICZuYnNwOwogICAgLSB2YXIgbGFzdCA9IDEKCWVhY2ggcmVjb3JkIGluIGRhdGEKICAg
ICAgdHIudHJfbm90dm90ZWQKICAgICAgICB0ZC5yYW5rICF7cmVjb3JkLmlkfQogICAgICAgIHRk
CiAgICAgICAgCWJhcmNvZGVpbWFnZSh0eXBlPSJjMzkiLGRhdGE9cmVjb3JkLnRhbm51bW1lciwi
c3R5bGUiPSJ3aWR0aDo3MG1tO2hlaWdodDo1bW07IikKICAgICAgdHIudHJfbm90dm90ZWQKICAg
ICAgICB0ZC5yYW5rICZuYnNwOwogICAgICAgIHRkCiAgICAgICAgCXNwYW4gIXtyZWNvcmQudGFu
bnVtbWVyfQogICAgICB0ci50cl9ub3R2b3RlZAogICAgICAgIHRkLnJhbmsgJm5ic3A7CiAgICAg
ICAgdGQgJm5ic3A7CgkJ') );

insert ignore into ds_pug_templates (name,id,note,template) values ('wm_berichte_tanboegen_tabelle','wm_berichte_tanboegen_tabelle',from_base64('d21fYmVyaWNodGVfdGFuYm9lZ2VuX3RhYmVsbGU='),from_base64( 'CnRhYmxlLmNhbmRpZGF0ZXRhYmxlCgl0cgogICAgCXRoLnJhbmsgTnIuCiAgICAJdGguYW56ZWln
ZV9uYW1lICZuYnNwOwogICAgLSB2YXIgbGFzdCA9IDEKCWVhY2ggcmVjb3JkIGluIGRhdGEKICAg
ICAgdHIudHJfbm90dm90ZWQKICAgICAgICB0ZC5yYW5rICF7cmVjb3JkLmlkfQogICAgICAgIHRk
CiAgICAgICAgCWJhcmNvZGVpbWFnZSh0eXBlPSJjMzkiLGRhdGE9cmVjb3JkLnRhbm51bW1lciwi
c3R5bGUiPSJ3aWR0aDo3MG1tO2hlaWdodDo1bW07IikKICAgICAgdHIudHJfbm90dm90ZWQKICAg
ICAgICB0ZC5yYW5rICZuYnNwOwogICAgICAgIHRkCiAgICAgICAgCXNwYW4gIXtyZWNvcmQudGFu
bnVtbWVyfQogICAgICB0ci50cl9ub3R2b3RlZAogICAgICAgIHRkLnJhbmsgJm5ic3A7CiAgICAg
ICAgdGQgJm5ic3A7CgkJ') );

