DELIMITER ;
-- create view if not exists `ds_renderer_stylesheet_attributes_dd` as select `ds_renderer_stylesheet_attributes`.`attribute` AS `attribute` from `ds_renderer_stylesheet_attributes` group by `ds_renderer_stylesheet_attributes`.`attribute`;
INSERT IGNORE INTO `ds_renderer_stylesheet` (`classname`, `group`) VALUES ('address',1),
('page',1),
('pagebackground',1),
('pagecontent',1),
('pageinfo',1),
('pagemargins',1),
('senderaddress',1),
('footerinfoblock',2),
('footerinfoblocklabel',2),
('footerinfoblockvalue',2),
('anzeige_name',3),
('candidatetable',3),
('hr_notvoted',3),
('number',3),
('rank',3),
('td_notvoted',3),
('number_re',4),
('printtable',4);
INSERT IGNORE INTO `ds_renderer_stylesheet_attributes` (`classname`, `attribute`, `values`, `enclose`) VALUES ('address','font-size','1em',''),
('address','font-weight','normal',''),
('address','height','27.3mm',''),
('address','left','25mm',''),
('address','overflow','hidden',''),
('address','padding-left','0mm',''),
('address','padding-top','0mm',''),
('address','position','fixed',''),
('address','top','17.5mm',''),
('address','width','80mm',''),
('anzahl','text-align','right',''),
('anzahl','width','14mm',''),
('anzeige_name','font-size','1.0em',''),
('artikel','text-align','left',''),
('bemerkung','font-size','0.8em',''),
('candidatetable','width','100%',''),
('debugborder','border','0px dashed cyan',''),
('epreis','text-align','right',''),
('epreis','width','2cm',''),
('foldmarks','border-bottom','0.1mm solid gray',''),
('foldmarks','border-top','0.1mm solid gray',''),
('foldmarks','font-size','1px',''),
('foldmarks','height','105mm',''),
('foldmarks','position','fixed',''),
('foldmarks','top','52mm',''),
('foldmarks','width','10mm',''),
('footerinfoblock','width','175mm',''),
('footerinfoblocklabel','text-align','right',''),
('footerinfoblocklabel','width','20mm',''),
('footerinfoblockvalue','text-align','right',''),
('footerinfoblockvalue','width','20mm',''),
('girocodeblock','bottom','-30mm',''),
('girocodeblock','position','fixed',''),
('girocodeblock','right','10mm',''),
('hr_notvoted','color','rgb(50,50,50)',''),
('infoblock','width','100%',''),
('infoblockvalue','text-align','right',''),
('netto','text-align','right',''),
('netto','width','18mm',''),
('number','text-align','right',''),
('number','width','25mm',''),
('number_re','text-align','right',''),
('page','font-family','DejaVu Sans','\''),
('page','font-size','8pt','\''),
('page','margin-bottom','25mm','\''),
('page','margin-left','0mm','\''),
('page','margin-right','0mm','\''),
('page','margin-top','27mm','\''),
('page','padding-left','25mm',''),
('page','padding-right','20mm',''),
('page','padding-top','10mm',''),
('pagebackground','bottom','0mm','\''),
('pagebackground','left','0mm','\''),
('pagebackground','position','fixed','\''),
('pagebackground','right','0mm','\''),
('pagebackground','top','0mm','\''),
('pagebackground','z-index','-1','\''),
('pagecontent','border','1px dashed black','\''),
('pagecontent','margin-left','25mm','\''),
('pagecontent','margin-right','10mm','\''),
('pagecontent','margin-top','70.46mm','\''),
('pagecontent','position','relative',''),
('pageinfo','position','fixed','\''),
('pageinfo','right','10mm','\''),
('pageinfo','text-align','right',''),
('pageinfo','top','-5mm','\''),
('pageinfo','width','75mm','\''),
('pagemargins','padding-bottom','5mm','\''),
('pagemargins','padding-left','25mm','\''),
('pagemargins','padding-right','15mm','\''),
('pagemargins','padding-top','10mm','\''),
('positiontable','width','100%',''),
('positiontable tr:first-child','border-top','0.5mm solid black',''),
('positiontable_header','border-bottom','0.5mm solid black',''),
('positiontable_header .header','border-bottom','0.2mm solid black',''),
('printtable','border','1px solid black',''),
('printtable','border-collapse','collapse',''),
('printtable','padding','5px',''),
('rank','color','rgb(90,90,90)',''),
('rank','padding-right','5mm',''),
('rank','text-align','right',''),
('rank','width','15mm',''),
('senderaddress','font-size','5pt','\''),
('senderaddress','left','25mm',''),
('senderaddress','position','fixed',''),
('senderaddress','top','10mm','\''),
('sp001','font-size','7pt',''),
('sp001','width','30mm',''),
('sp002','font-size','7pt',''),
('sp002','vertical-align','top',''),
('sp002','width','70mm',''),
('sp003','font-size','7pt',''),
('sp003','text-align','right',''),
('steuersatz','text-align','right',''),
('steuersatz','width','10mm',''),
('sumtablewrapper','border-top','0.2mm solid black',''),
('sumtablewrapper','width','100%',''),
('sumtext','text-align','right',''),
('sumtext','width','30mm',''),
('sumvalue','text-align','right',''),
('sumvalue','width','18mm',''),
('td_notvoted','border-bottom','0.1mm solid black',''),
('td_notvoted','font-size','0.5em',''),
('total .sumtext','border-bottom','0.2mm solid black',''),
('total .sumtext','font-weight','bold',''),
('total .sumvalue','border-bottom','0.2mm solid black',''),
('total .sumvalue','font-weight','bold','');
INSERT IGNORE INTO `ds_renderer_stylesheet_groups` (`id`, `name`) VALUES (2,'FOOT'),
(1,'LETTER-ISO-5008'),
(4,'PROTOKOLLE'),
(3,'TABLE');
