delimiter ;


create or replace view view_protokoll_online_erwartet as
select 
sz.ridx,
sz.name,
sz.id,

ws.c erwartet,
wst.c testdaten_erwartet,
bb.anzahl gueltig,
ebb.anzahl enthaltung,
ubb.anzahl ungueltig

from 

(select * from stimmzettel) sz
left join (select stimmzettel,count(*) c from wahlschein where abgabetyp = '2|0' and wahlscheinstatus='2|0' 
    and testdaten =0 
group by stimmzettel) ws on ws.stimmzettel = sz.ridx
left join (select stimmzettel,count(*) c from wahlschein where abgabetyp = '2|0' and wahlscheinstatus='2|0'
    and testdaten =1 
 group by stimmzettel) wst on wst.stimmzettel = sz.ridx
left join (select stimmzettel,anzahl from ballotbox_decrypted_sum where status = 'gültig') bb on bb.stimmzettel = sz.ridx
left join (select stimmzettel,anzahl from ballotbox_decrypted_sum where status = 'Enthaltung') ebb on ebb.stimmzettel = sz.ridx
left join (select stimmzettel,anzahl from ballotbox_decrypted_sum where status = 'ungültig') ubb on ubb.stimmzettel = sz.ridx

;


insert ignore into ds_pug_templates (name,id,note,template) values ('wm_berichte_erwartet_online','wm_berichte_erwartet_online',from_base64('d21fYmVyaWNodGVfZXJ3YXJ0ZXRfb25saW5l'),from_base64( 'c3R5bGUuCiAgICAJQHBhZ2Uge3NpemU6IEE0IGxhbmRzY2FwZTsgfQo6cGhwCiAgICAkZGF0YSA9
XFR1YWxvXE9mZmljZVxEU1xEU1RhYmxlOjppbnN0YW5jZSgndmlld19wcm90b2tvbGxfb25saW5l
X2Vyd2FydGV0JyktPnJlYWQoKS0+Z2V0KCk7Ci8vIGQgcyh0YWJsZW5hbWU9InZpZXdfc3RpbW1l
bmFuemFobF9yYW5raW5nX2xvc19tb25pdG9yX2xpc3QiLHRlbXBsYXRlPSJ3bV9iZXJpY2h0ZV9l
cndhcnRldF9vdXRwdXQiKQpkaXYoc3R5bGU9Im1hcmdpbi1sZWZ0OiAwLjBjbTsgIikKCS0gdmFy
IHN1bV9lcncgPSAwCiAgICAtIHZhciBzdW1fZ2VzID0gMAogICAgLSB2YXIgc3VtX3VuZyA9IDAK
ICAgIC0gdmFyIHN1bV9rb24gPSAwCiAgICAtIHZhciBnZXNfcW91ID0gMAogICAgLSB2YXIgc3Vt
X2Vyd3QgPSAwCiAgICAtIHZhciBnZXNfa29uID0gMAogICAgLSB2YXIgc3VtX2VudCA9IDAKICAg
IC8vIGgxKHN0eWxlPSJjb2xvcjpyZWQ7IikgICEhISBBY2h0dW5nIFRlc3RkYXRlbiBub2NoIGVu
dGhhbHRlbiAhISEKICAgIAlicgogICAgICAgIHNwYW4gdmlldzogJ3ZpZXdfc3RpbW1lbmFuemFo
bF9yYW5raW5nX2xvc19tb25pdG9yX2xpc3RfZXJ3YXJ0ZXQnICggYW5kIGB3YWhsc2NoZWluYC5g
dGVzdGRhdGVuYCA9IDApCiAgICAJYnIgCiAgICAgICAgc3BhbiBwdWc6IHdtX2JlcmljaHRlX2Vy
d2FydGV0X291dHB1dAoJdGFibGUucHJpbnR0YWJsZShzdHlsZT0id2lkdGg6IDEwMCU7IikKICAg
IAl0aGVhZAoJCQl0ci5wcmludHRhYmxlCiAgICAJCQl0aC5wcmludHRhYmxlIFN0aW1temV0dGVs
Z3J1cHBlCgkgICAgICAgIAl0aC5wcmludHRhYmxlLnRkbnVtYmVyd2lkdGggRXJ3YXJ0ZXQKICAg
IAkJCXRoLnByaW50dGFibGUudGRudW1iZXJ3aWR0aCBUZXN0ZGF0ZW4KICAgIAkJCXRoLnByaW50
dGFibGUudGRudW1iZXJ3aWR0aCBHw7xsdGlnCiAgICAgICAgCQl0aC5wcmludHRhYmxlLnRkbnVt
YmVyd2lkdGggVW5nw7xsdGlnCiAgICAgICAgCQl0aC5wcmludHRhYmxlLnRkbnVtYmVyd2lkdGgg
RW50aGFsdHVuZ2VuCiAgICAgICAgCQl0aC5wcmludHRhYmxlLnRkbnVtYmVyd2lkdGggS29udHJv
bGxlCiAgICAgICAgICAgICAgICB0aC5wcmludHRhYmxlKHN0eWxlPSJ3aWR0aDoyY207IikgUXVv
dGUKCQl0Ym9keShzdHlsZT0ibWFyZ2luLXRvcDogMC41Y207IikKCQkJZWFjaCByZWNvcmQgaW4g
ZGF0YQogICAgICAgICAgICAgICAgLSBrb250cm9sbGUgPSBpbnR2YWwocmVjb3JkLmVyd2FydGV0
KSAtIGludHZhbChyZWNvcmQuZ3VlbHRpZykgLSBpbnR2YWwocmVjb3JkLnVuZ3VlbHRpZykgLWlu
dHZhbChyZWNvcmQuZW50aGFsdHVuZykKCQkJCS0gc3VtX2VydyA9IHN1bV9lcncgKyBpbnR2YWwo
cmVjb3JkLmVyd2FydGV0KSAgCgkJCQktIHN1bV9lcnd0ID0gc3VtX2Vyd3QgKyBpbnR2YWwocmVj
b3JkLnRlc3RkYXRlbl9lcndhcnRldCkKICAgICAgICAgICAgCS0gc3VtX2dlcyA9IHN1bV9nZXMg
KyBpbnR2YWwocmVjb3JkLmd1ZWx0aWcpCiAgICAgICAgICAgIAktIHN1bV91bmcgPSBzdW1fdW5n
ICsgaW50dmFsKHJlY29yZC51bmd1ZWx0aWcpCiAgICAgICAgICAgIAktIHN1bV9lbnQgPSBzdW1f
ZW50ICsgaW50dmFsKHJlY29yZC5lbnRoYWx0dW5nKQogICAgICAgICAgICAJLSBzdW1fa29uID0g
c3VtX2tvbiArIGludHZhbChrb250cm9sbGUpCiAgICAgICAgICAgICAgICAtIHFvdSA9IDAKICAg
ICAgICAgICAgICAgIC0geCA9IGludHZhbChyZWNvcmQuZXJ3YXJ0ZXQpIAogICAgICAgICAgICAg
ICAgaWYgKHghPTApCiAgICAgICAgICAgICAgICAgICAgLSBxb3UgPSAoKGludHZhbChyZWNvcmQu
Z3VlbHRpZykgLSBpbnR2YWwocmVjb3JkLnVuZ3VlbHRpZykgLWludHZhbChyZWNvcmQuZW50aGFs
dHVuZykpLyB4ICkKICAgICAgICAgICAgCXRyCiAgICAgICAgICAgIAkJdGQucHJpbnR0YWJsZSAh
e3JlY29yZC5uYW1lfQogICAgICAgICAgICAgICAgCXRkLnByaW50dGFibGUubnVtYmVyX3JlICF7
bnVtYmVyX2Zvcm1hdChyZWNvcmQuZXJ3YXJ0ZXQsMCwnLCcsJy4nKX0KICAgICAgICAgICAgICAg
IAl0ZC5wcmludHRhYmxlLm51bWJlcl9yZSAhe251bWJlcl9mb3JtYXQocmVjb3JkLnRlc3RkYXRl
bl9lcndhcnRldCwwLCcsJywnLicpfQogICAgICAgICAgIAkJCXRkLnByaW50dGFibGUubnVtYmVy
X3JlICF7bnVtYmVyX2Zvcm1hdChyZWNvcmQuZ3VlbHRpZywwLCcsJywnLicpfQogICAgICAgICAg
IAkJCXRkLnByaW50dGFibGUubnVtYmVyX3JlICF7bnVtYmVyX2Zvcm1hdChyZWNvcmQudW5ndWVs
dGlnLDAsJywnLCcuJyl9CiAgICAgICAgICAgCQkJdGQucHJpbnR0YWJsZS5udW1iZXJfcmUgIXtu
dW1iZXJfZm9ybWF0KHJlY29yZC5lbnRoYWx0dW5nLDAsJywnLCcuJyl9CiAgICAgICAgICAgICAg
ICAJdGQucHJpbnR0YWJsZS5udW1iZXJfcmUgIXtudW1iZXJfZm9ybWF0KGtvbnRyb2xsZSwwLCcs
JywnLicpfQogICAgICAgICAgICAgICAgCXRkLnByaW50dGFibGUubnVtYmVyX3JlICF7bnVtYmVy
X2Zvcm1hdChxb3UqMTAwLDIsJywnLCcuJyl9ICUKICAgICAgICAgICAgLSBnZXNfcW91ID0gMAog
ICAgICAgICAgICBpZiAoc3VtX2VydyE9MCkKICAgICAgICAgICAgICAgIC0gZ2VzX3FvdSA9ICgo
c3VtX2dlcytzdW1fdW5nK3N1bV9lbnQpL3N1bV9lcncpCiAgICAgICAgICAgIC0gZ2VzX2tvbiA9
IChzdW1fZXJ3LXN1bV91bmctc3VtX2VudC1zdW1fZ2VzKQogICAgICAgICAgICB0cgogICAgICAg
ICAgICAgICAgdGQucHJpbnR0YWJsZSBTdW1tZW4KICAgICAgICAgICAgICAgIHRkLnByaW50dGFi
bGUubnVtYmVyX3JlICF7bnVtYmVyX2Zvcm1hdChzdW1fZXJ3LDAsJywnLCcuJyl9CiAgICAgICAg
ICAgICAgICB0ZC5wcmludHRhYmxlLm51bWJlcl9yZSAhe251bWJlcl9mb3JtYXQoc3VtX2Vyd3Qs
MCwnLCcsJy4nKX0KICAgICAgICAgICAgICAgIHRkLnByaW50dGFibGUubnVtYmVyX3JlICF7bnVt
YmVyX2Zvcm1hdChzdW1fZ2VzLDAsJywnLCcuJyl9CiAgICAgICAgICAgICAgICB0ZC5wcmludHRh
YmxlLm51bWJlcl9yZSAhe251bWJlcl9mb3JtYXQoc3VtX3VuZywwLCcsJywnLicpfQogICAgICAg
ICAgICAgICAgdGQucHJpbnR0YWJsZS5udW1iZXJfcmUgIXtudW1iZXJfZm9ybWF0KHN1bV9lbnQs
MCwnLCcsJy4nKX0KICAgICAgICAgICAgICAgIHRkLnByaW50dGFibGUubnVtYmVyX3JlICF7bnVt
YmVyX2Zvcm1hdChnZXNfa29uLDAsJywnLCcuJyl9CiAgICAgICAgICAgICAgICB0ZC5wcmludHRh
YmxlLm51bWJlcl9yZSAhe251bWJlcl9mb3JtYXQoZ2VzX3FvdSoxMDAsMiwnLCcsJy4nKX0lCg==') );