DELIMITER ;
INSERT INTO `ds` (`table_name`, `title`, `reorderfield`, `use_history`, `searchfield`, `displayfield`, `sortfield`, `searchany`, `hint`, `overview_tpl`, `sync_table`, `writetable`, `globalsearch`, `listselectionmodel`, `sync_view`, `syncable`, `cssstyle`, `alternativeformxtype`, `read_table`, `class_name`, `special_add_panel`, `existsreal`, `character_set_name`, `read_filter`, `listxtypeprefix`, `phpexporter`, `phpexporterfilename`, `combined`, `default_pagesize`, `allowForm`, `listviewbaseclass`, `showactionbtn`, `modelbaseclass`) VALUES ('wahlscheinstatus','Wahlscheinstatus','',0,'name','name','id',1,'Der Wahlscheinstatus gibt den Status der Wahlbeteiligung zurück.','','','',1,'','',0,'','','','Wahlsystem','',1,'','','listview','XlsxWriter','wahlscheinstatus',0,1000,0,'Tualo.DataSets.ListView',1,'Tualo.DataSets.model.Basic') ON DUPLICATE KEY UPDATE title=VALUES(title), reorderfield=VALUES(reorderfield), use_history=VALUES(use_history), searchfield=VALUES(searchfield), displayfield=VALUES(displayfield), sortfield=VALUES(sortfield), searchany=VALUES(searchany), hint=VALUES(hint), overview_tpl=VALUES(overview_tpl), sync_table=VALUES(sync_table), writetable=VALUES(writetable), globalsearch=VALUES(globalsearch), listselectionmodel=VALUES(listselectionmodel), sync_view=VALUES(sync_view), syncable=VALUES(syncable), cssstyle=VALUES(cssstyle), alternativeformxtype=VALUES(alternativeformxtype), read_table=   VALUES(read_table), class_name=VALUES(class_name), special_add_panel=VALUES(special_add_panel), existsreal=VALUES(existsreal), character_set_name=VALUES(character_set_name), read_filter=VALUES(read_filter), listxtypeprefix=VALUES(listxtypeprefix), phpexporter=VALUES(phpexporter), phpexporterfilename=VALUES(phpexporterfilename), combined=VALUES(combined), default_pagesize=VALUES(default_pagesize), allowForm=VALUES(allowForm), listviewbaseclass=VALUES(listviewbaseclass), showactionbtn=VALUES(showactionbtn), modelbaseclass=VALUES(modelbaseclass);
INSERT  IGNORE INTO `ds_column` (`table_name`, `column_name`, `default_value`, `default_max_value`, `default_min_value`, `update_value`, `is_primary`, `syncable`, `referenced_table`, `referenced_column_name`, `is_nullable`, `is_referenced`, `writeable`, `note`, `data_type`, `column_key`, `column_type`, `character_maximum_length`, `numeric_precision`, `numeric_scale`, `character_set_name`, `privileges`, `existsreal`, `deferedload`, `hint`, `fieldtype`) VALUES ('wahlscheinstatus','aktiv',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'tinyint','','tinyint(4)',NULL,3,0,NULL,'select,insert,update,references',1,NULL,NULL,''),
('wahlscheinstatus','barcode',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'varchar','','varchar(255)',255,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('wahlscheinstatus','beschreibung',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'varchar','','varchar(4000)',4000,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('wahlscheinstatus','farbe',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'varchar','','varchar(255)',255,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('wahlscheinstatus','fibukonto',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'varchar','','varchar(20)',20,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('wahlscheinstatus','id',NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,'NO',NULL,1,NULL,'int','PRI','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,NULL,NULL,''),
('wahlscheinstatus','insert_date',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NO',NULL,1,NULL,'date','','date',NULL,NULL,NULL,NULL,'select,insert,update,references',1,NULL,NULL,''),
('wahlscheinstatus','insert_time',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'time','','time',NULL,NULL,NULL,NULL,'select,insert,update,references',1,NULL,NULL,''),
('wahlscheinstatus','kostenstelle',NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,'NO',NULL,1,NULL,'int','PRI','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,NULL,NULL,''),
('wahlscheinstatus','login',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NO',NULL,1,NULL,'varchar','','varchar(255)',255,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('wahlscheinstatus','name',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'varchar','','varchar(255)',255,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('wahlscheinstatus','ohne_wahlberechtigten',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'varchar','','varchar(255)',255,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('wahlscheinstatus','ridx',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'varchar','UNI','varchar(12)',12,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('wahlscheinstatus','steuerschluessel',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'varchar','','varchar(20)',20,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('wahlscheinstatus','sz_count',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,NULL,NULL,''),
('wahlscheinstatus','update_date',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NO',NULL,1,NULL,'date','','date',NULL,NULL,NULL,NULL,'select,insert,update,references',1,NULL,NULL,''),
('wahlscheinstatus','update_time',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'time','','time',NULL,NULL,NULL,NULL,'select,insert,update,references',1,NULL,NULL,'');
INSERT  IGNORE INTO `ds_column_list_label` (`table_name`, `column_name`, `language`, `label`, `xtype`, `editor`, `position`, `summaryrenderer`, `renderer`, `summarytype`, `hidden`, `active`, `filterstore`, `grouped`, `flex`, `direction`, `align`, `listfiltertype`, `hint`) VALUES ('wahlscheinstatus','aktiv','DE','Aktiv','booleancolumn','',999,NULL,'',NULL,0,1,'',0,1.00,'ASC','left','',''),
('wahlscheinstatus','barcode','DE','Code','gridcolumn','',999,NULL,'',NULL,0,1,'',0,1.00,'ASC','left','',''),
('wahlscheinstatus','farbe','DE','Farbe','rgbcolorcolumn','',999,NULL,'',NULL,0,1,'',0,1.00,'ASC','left','',''),
('wahlscheinstatus','id','DE','ID','gridcolumn','',999,NULL,'',NULL,0,1,'',0,1.00,'ASC','left','',''),
('wahlscheinstatus','kostenstelle','DE','kostenstelle','gridcolumn','',0,'','','',0,1,'',0,1.00,'ASC','left','',''),
('wahlscheinstatus','name','DE','Name','gridcolumn','',999,NULL,'',NULL,0,1,'',0,1.00,'ASC','left','',''),
('wahlscheinstatus','ohne_wahlberechtigten','DE','ohne WB','booleancolumn','',999,NULL,'',NULL,0,1,'',0,1.00,'ASC','left','',''),
('wahlscheinstatus','ridx','DE','ridx','gridcolumn','',999,'','','',1,1,'',0,0.00,'','','','\'\'');
INSERT  IGNORE INTO `ds_column_form_label` (`table_name`, `column_name`, `language`, `label`, `xtype`, `field_path`, `position`, `hidden`, `active`, `allowempty`, `fieldgroup`, `flex`, `hint`) VALUES ('wahlscheinstatus','aktiv','DE','Aktiv','checkbox','Allgemein',2,0,1,1,'',1.00,''),
('wahlscheinstatus','barcode','DE','barcode','textfield','Allgemein',4,0,1,0,'',1.00,''),
('wahlscheinstatus','beschreibung','DE','beschreibung','displayfield','Allgemein',9,1,0,0,'',1.00,''),
('wahlscheinstatus','farbe','DE','Farbe','tualocolors','Allgemein',5,0,1,1,'',1.00,''),
('wahlscheinstatus','fibukonto','DE','fibukonto','displayfield','Allgemein',14,1,0,0,'',1.00,''),
('wahlscheinstatus','id','DE','ID','displayfield','Allgemein',1,0,1,1,'',1.00,''),
('wahlscheinstatus','insert_date','DE','insert_date','displayfield','Allgemein',10,1,0,0,'',1.00,''),
('wahlscheinstatus','insert_time','DE','insert_time','displayfield','Allgemein',7,1,0,0,'',1.00,''),
('wahlscheinstatus','kostenstelle','DE','kostenstelle','displayfield','Allgemein',0,0,1,1,'',1.00,''),
('wahlscheinstatus','login','DE','login','displayfield','Allgemein',12,1,0,0,'',1.00,''),
('wahlscheinstatus','name','DE','Name','textfield','Allgemein',3,0,1,1,'',1.00,''),
('wahlscheinstatus','ohne_wahlberechtigten','DE','ohne WB','checkbox','Allgemein',6,0,1,1,'',1.00,''),
('wahlscheinstatus','ridx','DE','ridx','displayfield','Allgemein',15,1,0,0,'',1.00,''),
('wahlscheinstatus','steuerschluessel','DE','steuerschluessel','displayfield','Allgemein',11,1,0,0,'',1.00,''),
('wahlscheinstatus','sz_count','DE','sz_count','displayfield','Allgemein',8,1,0,0,'',1.00,''),
('wahlscheinstatus','update_date','DE','update_date','displayfield','Allgemein',16,1,0,0,'',1.00,''),
('wahlscheinstatus','update_time','DE','update_time','displayfield','Allgemein',13,1,0,0,'',1.00,'');
INSERT  IGNORE INTO `ds_dropdownfields` (`table_name`, `name`, `idfield`, `displayfield`, `filterconfig`) VALUES ('wahlscheinstatus','id','id','name',''),
('wahlscheinstatus','name','name','name',''),
('wahlscheinstatus','RIDX','ridx','name',NULL),
('wahlscheinstatus','StatusRidx','ridx','name',NULL);
INSERT  IGNORE INTO `ds_access` (`role`, `table_name`, `read`, `write`, `delete`, `append`, `existsreal`) VALUES ('administration','wahlscheinstatus',1,1,1,1,1);
